name: Trigger /quotes/count

on:
  schedule:
    - cron: '38 2 * * *'  # 08:08 AM IST
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call GET /quotes/count
        run: curl -X GET http://172.188.80.68/mcp1/quotes/count
