name: Trigger /track/batch-image-alt

on:
  schedule:
    - cron: '10 3 * * *'  # 08:40 AM IST
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call POST /track/batch-image-alt
        run: curl -X POST http://172.188.80.68/mcp1/track/batch-image-alt
