name: Trigger /azure/download_jsonl_data

on:
  schedule:
    - cron: '18 3 * * *'  # 08:48 AM IST
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call GET /azure/download_jsonl_data
        run: curl -X GET http://172.188.80.68/mcp1/azure/download_jsonl_data
