name: Trigger /merge_text/merge-textual-data

on:
  schedule:
    - cron: '26 3 * * *'  # 08:56 AM IST
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call POST /merge_text/merge-textual-data
        run: curl -X POST http://172.188.80.68/mcp1/merge_text/merge-textual-data
