name: Trigger /match/match-alt-text

on:
  schedule:
    - cron: '34 3 * * *'  # 09:04 AM IST
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call POST /match/match-alt-text
        run: curl -X POST http://172.188.80.68/mcp1/match/match-alt-text
