name: Trigger /resizer/generate-resized-urls

on:
  schedule:
    - cron: '42 3 * * *'  # 09:12 AM IST
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call POST /resizer/generate-resized-urls
        run: curl -X POST http://172.188.80.68/mcp1/resizer/generate-resized-urls
