name: Trigger /videometa/video-meta

on:
  schedule:
    - cron: '58 3 * * *'  # 09:28 AM IST
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call POST /videometa/video-meta
        run: curl -X POST http://172.188.80.68/mcp1/videometa/video-meta
