name: Trigger /modify_column/clean-video-meta

on:
  schedule:
    - cron: '6 4 * * *'  # 09:36 AM IST
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call POST /modify_column/clean-video-meta
        run: curl -X POST http://172.188.80.68/mcp1/modify_column/clean-video-meta
