name: Trigger /rotate/

on:
  schedule:
    - cron: '22 4 * * *'  # 09:52 AM IST
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call POST /rotate/
        run: curl -X POST http://172.188.80.68/mcp1/rotate/
